In [1]:
#Importing
import pandas as pd

In [4]:
df = pd.read_csv("urldata.csv")
df.head(10)

   Unnamed: 0                        url   label  result
0           0     https://www.google.com  benign       0
1           1    https://www.youtube.com  benign       0
2           2   https://www.facebook.com  benign       0
3           3      https://www.baidu.com  benign       0
4           4  https://www.wikipedia.org  benign       0
5           5     https://www.reddit.com  benign       0
6           6      https://www.yahoo.com  benign       0
7           7   https://www.google.co.in  benign       0
8           8         https://www.qq.com  benign       0
9           9     https://www.amazon.com  benign       0

In [ ]:
#Dropping unnamed:0
df.drop('Unnamed: 0',axis=1,inplace = True)
df[10]